### ISSUE TITLE
Create pre-match checklist

### ISSUE THREAD

**Issue by rivques** [chsbacon/FTC-CENTERSTAGE-7080#38]

**Comment by rivques** [comment]
## pre match
- [ ] Ensure all nuts are tight, especially those for the hub mount.
- [ ] Ensure correct Team Indicators are attached.
- [ ] Ensure robot has fresh battery.
- [ ] Power on robot.
- [ ] Connect controllers to driver hub. Ensure drivers know which is which.
- [ ] Move arm to pit.
- [ ] Ensure pulley is taut.
- [ ] select correct opmode in picker.
- [ ] Person A: tilt the robot onto its side.
- [ ] Person B: place yellow pixel in correct orientation in claw.
- [ ] Person C: INIT OPMODE.
- [ ] Person B: Ensure claw closed firmly around yellow pixel.
- [ ] Person A: Place robot back on ground.
- [ ] Align robot for game start (centered on back wall of its tile).
- [ ] Place purple pixel in shovel.
- [ ] Select "camera stream" on Driver Hub. Move camera so all spike mark locations are correctly visible.
- [ ] Select "camera stream" again.
- [ ] Confirm pulley is still taut and yellow pixel is still held.
- [ ] Robot is ready for MATCH START.

## start of teleop
- [ ] Select, init, and play "IntegratedTeleOp."
- [ ] Driver: If yaw is not correct: use X and B to adjust yaw, then reset yaw.
- [ ] Operator: If arm has malfunctioned: attempt to fix with manual override. if unsuccessful: communicate limitations to Driver and Team Coach. Team Coach: communicate this to Alliance Member.

## post match
- [ ] Stop IntegratedTeleOp.
- [ ] When refs allow: Shake hands with opponents and teammates.
- [ ] Remove robot from truss (if hanging).
- [ ] Turn off robot.
- [ ] Make pulley taut. Move arm to pit.
- [ ] Retrieve Team Prop. Retrieve Drone (if used).
- [ ] Place robot on cart, move to pit.
- [ ] Charge the battery.

**Comment by rivques** [comment]
created

**Comment by rivques** [comment]
will redo when we get closer to comp. to add to list: drone loading procedure, emphasize alignment before auto init
